# Generated by Django 3.0 on 2022-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220422_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=10)),
                ('installment', models.CharField(max_length=2)),
                ('penalty', models.CharField(max_length=5)),
                ('dop', models.DateField()),
                ('p_status', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
