# Generated by Django 3.0 on 2022-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='desc',
            field=models.TextField(),
        ),
    ]
